module.exports = {
    "audio_features": [
      {
        "danceability": 0.627,
        "energy": 0.771,
        "key": 0,
        "loudness": -5.281,
        "mode": 0,
        "speechiness": 0.0605,
        "acousticness": 0.0867,
        "instrumentalness": 0.514,
        "liveness": 0.073,
        "valence": 0.678,
        "tempo": 143.988,
        "type": "audio_features",
        "id": "2EU6Mfs6b0N08G6lOXDt5p",
        "uri": "spotify:track:2EU6Mfs6b0N08G6lOXDt5p",
        "track_href": "https://api.spotify.com/v1/tracks/2EU6Mfs6b0N08G6lOXDt5p",
        "analysis_url": "https://api.spotify.com/v1/audio-analysis/2EU6Mfs6b0N08G6lOXDt5p",
        "duration_ms": 267517,
        "time_signature": 4,
        "track_name": "Too Late",
        "artist": 'Tourist'
      },
      {
        "danceability": 0.638,
        "energy": 0.632,
        "key": 9,
        "loudness": -7.589,
        "mode": 1,
        "speechiness": 0.029,
        "acousticness": 0.000904,
        "instrumentalness": 0.0406,
        "liveness": 0.115,
        "valence": 0.349,
        "tempo": 114.992,
        "type": "audio_features",
        "id": "3AAdbLZWOptsP8ViSj71RD",
        "uri": "spotify:track:3AAdbLZWOptsP8ViSj71RD",
        "track_href": "https://api.spotify.com/v1/tracks/3AAdbLZWOptsP8ViSj71RD",
        "analysis_url": "https://api.spotify.com/v1/audio-analysis/3AAdbLZWOptsP8ViSj71RD",
        "duration_ms": 306532,
        "time_signature": 4,
        "track_name": "Realiti",
        "artist": 'Grimes'
      },
      {
        "danceability": 0.475,
        "energy": 0.51,
        "key": 8,
        "loudness": -6.563,
        "mode": 1,
        "speechiness": 0.0274,
        "acousticness": 0.719,
        "instrumentalness": 0.00000968,
        "liveness": 0.112,
        "valence": 0.226,
        "tempo": 79.9,
        "type": "audio_features",
        "id": "054ybW7shxoj7HfEyggaCj",
        "uri": "spotify:track:054ybW7shxoj7HfEyggaCj",
        "track_href": "https://api.spotify.com/v1/tracks/054ybW7shxoj7HfEyggaCj",
        "analysis_url": "https://api.spotify.com/v1/audio-analysis/054ybW7shxoj7HfEyggaCj",
        "duration_ms": 277613,
        "time_signature": 4,
        "track_name": "Spanish Sahara",
        "artist": 'Foals'
      },
      {
        "danceability": 0.545,
        "energy": 0.948,
        "key": 11,
        "loudness": -5.098,
        "mode": 1,
        "speechiness": 0.0781,
        "acousticness": 0.00334,
        "instrumentalness": 0.379,
        "liveness": 0.226,
        "valence": 0.357,
        "tempo": 141.498,
        "type": "audio_features",
        "id": "6qptzOQGAT0YZjhIsgsuAM",
        "uri": "spotify:track:6qptzOQGAT0YZjhIsgsuAM",
        "track_href": "https://api.spotify.com/v1/tracks/6qptzOQGAT0YZjhIsgsuAM",
        "analysis_url": "https://api.spotify.com/v1/audio-analysis/6qptzOQGAT0YZjhIsgsuAM",
        "duration_ms": 279800,
        "time_signature": 4,
        "track_name": "Firestarter",
        "artist": 'The Prodigy'
      }
    ]
}