module.exports = {
  'audio_features': [
    {
      'danceability': 0.627,
      'energy': 0.771,
      'key': 0,
      'loudness': -5.281,
      'mode': 0,
      'speechiness': 0.0605,
      'acousticness': 0.0867,
      'instrumentalness': 0.514,
      'liveness': 0.073,
      'valence': 0.678,
      'tempo': 143.988,
      'type': 'audio_features',
      'id': '2EU6Mfs6b0N08G6lOXDt5p',
      'uri': 'spotify:track:2EU6Mfs6b0N08G6lOXDt5p',
      'track_href': 'https://api.spotify.com/v1/tracks/2EU6Mfs6b0N08G6lOXDt5p',
      'analysis_url': 'https://api.spotify.com/v1/audio-analysis/2EU6Mfs6b0N08G6lOXDt5p',
      'duration_ms': 267517,
      'time_signature': 4,
      'track_name': 'Too Late',
      'artist': 'Tourist'
    },
    {
      'danceability': 0.638,
      'energy': 0.632,
      'key': 9,
      'loudness': -7.589,
      'mode': 1,
      'speechiness': 0.029,
      'acousticness': 0.000904,
      'instrumentalness': 0.0406,
      'liveness': 0.115,
      'valence': 0.349,
      'tempo': 114.992,
      'type': 'audio_features',
      'id': '3AAdbLZWOptsP8ViSj71RD',
      'uri': 'spotify:track:3AAdbLZWOptsP8ViSj71RD',
      'track_href': 'https://api.spotify.com/v1/tracks/3AAdbLZWOptsP8ViSj71RD',
      'analysis_url': 'https://api.spotify.com/v1/audio-analysis/3AAdbLZWOptsP8ViSj71RD',
      'duration_ms': 306532,
      'time_signature': 4,
      'track_name': 'Realiti',
      'artist': 'Grimes'
    },
    {
      'danceability': 0.475,
      'energy': 0.51,
      'key': 8,
      'loudness': -6.563,
      'mode': 1,
      'speechiness': 0.0274,
      'acousticness': 0.719,
      'instrumentalness': 0.00000968,
      'liveness': 0.112,
      'valence': 0.226,
      'tempo': 79.9,
      'type': 'audio_features',
      'id': '054ybW7shxoj7HfEyggaCj',
      'uri': 'spotify:track:054ybW7shxoj7HfEyggaCj',
      'track_href': 'https://api.spotify.com/v1/tracks/054ybW7shxoj7HfEyggaCj',
      'analysis_url': 'https://api.spotify.com/v1/audio-analysis/054ybW7shxoj7HfEyggaCj',
      'duration_ms': 277613,
      'time_signature': 4,
      'track_name': 'Spanish Sahara',
      'artist': 'Foals'
    },
    {
      'danceability': 0.545,
      'energy': 0.948,
      'key': 11,
      'loudness': -5.098,
      'mode': 1,
      'speechiness': 0.0781,
      'acousticness': 0.00334,
      'instrumentalness': 0.379,
      'liveness': 0.226,
      'valence': 0.357,
      'tempo': 141.498,
      'type': 'audio_features',
      'id': '6qptzOQGAT0YZjhIsgsuAM',
      'uri': 'spotify:track:6qptzOQGAT0YZjhIsgsuAM',
      'track_href': 'https://api.spotify.com/v1/tracks/6qptzOQGAT0YZjhIsgsuAM',
      'analysis_url': 'https://api.spotify.com/v1/audio-analysis/6qptzOQGAT0YZjhIsgsuAM',
      'duration_ms': 279800,
      'time_signature': 4,
      'track_name': 'Firestarter',
      'artist': 'The Prodigy'
    },
    {
      'danceability': 0.543,
      'energy': 0.87,
      'key': 9,
      'loudness': -6.514,
      'mode': 1,
      'speechiness': 0.0428,
      'acousticness': 0.358,
      'instrumentalness': 0.000939,
      'liveness': 0.792,
      'valence': 0.754,
      'tempo': 100.804,
      'type': 'audio_features',
      'id': '0GjEhVFGZW8afUYGChu3Rr',
      'uri': 'spotify:track:0GjEhVFGZW8afUYGChu3Rr',
      'track_href': 'https://api.spotify.com/v1/tracks/0GjEhVFGZW8afUYGChu3Rr',
      'analysis_url': 'https://api.spotify.com/v1/audio-analysis/0GjEhVFGZW8afUYGChu3Rr',
      'duration_ms': 230400,
      'time_signature': 4,
      'track_name': 'Dancing Queen',
      'artist': 'ABBA'
    },
    {
      'danceability': 0.414,
      'energy': 0.404,
      'key': 0,
      'loudness': -9.928,
      'mode': 0,
      'speechiness': 0.0499,
      'acousticness': 0.271,
      'instrumentalness': 0,
      'liveness': 0.3,
      'valence': 0.224,
      'tempo': 71.105,
      'type': 'audio_features',
      'id': '4u7EnebtmKWzUH433cf5Qv',
      'uri': 'spotify:track:4u7EnebtmKWzUH433cf5Qv',
      'track_href': 'https://api.spotify.com/v1/tracks/4u7EnebtmKWzUH433cf5Qv',
      'analysis_url': 'https://api.spotify.com/v1/audio-analysis/4u7EnebtmKWzUH433cf5Qv',
      'duration_ms': 354320,
      'time_signature': 4,
      'track_name': 'Bohemian Rhapsody',
      'artist': 'Queen'
    },
    {
      'danceability': 0.554,
      'energy': 0.772,
      'key': 7,
      'loudness': -4.821,
      'mode': 0,
      'speechiness': 0.0418,
      'acousticness': 0.00487,
      'instrumentalness': 0.0000066,
      'liveness': 0.354,
      'valence': 0.455,
      'tempo': 179.984,
      'type': 'audio_features',
      'id': '6F5c58TMEs1byxUstkzVeM',
      'uri': 'spotify:track:6F5c58TMEs1byxUstkzVeM',
      'track_href': 'https://api.spotify.com/v1/tracks/6F5c58TMEs1byxUstkzVeM',
      'analysis_url': 'https://api.spotify.com/v1/audio-analysis/6F5c58TMEs1byxUstkzVeM',
      'duration_ms': 223546,
      'time_signature': 4,
      'track_name': 'Roar',
      'artist': 'Katy Perry'
    },
    {
      'danceability': 0.86,
      'energy': 0.907,
      'key': 2,
      'loudness': -3.321,
      'mode': 1,
      'speechiness': 0.0407,
      'acousticness': 0.279,
      'instrumentalness': 0.693,
      'liveness': 0.0648,
      'valence': 0.786,
      'tempo': 138.045,
      'type': 'audio_features',
      'id': '0Bo5fjMtTfCD8vHGebivqc',
      'uri': 'spotify:track:0Bo5fjMtTfCD8vHGebivqc',
      'track_href': 'https://api.spotify.com/v1/tracks/0Bo5fjMtTfCD8vHGebivqc',
      'analysis_url': 'https://api.spotify.com/v1/audio-analysis/0Bo5fjMtTfCD8vHGebivqc',
      'duration_ms': 168880,
      'time_signature': 4,
      'track_name': 'Axel F',
      'artist': 'Crazy Frog'
    },
    {
      'danceability': 0.708,
      'energy': 0.843,
      'key': 7,
      'loudness': -2.66,
      'mode': 1,
      'speechiness': 0.314,
      'acousticness': 0.397,
      'instrumentalness': 0,
      'liveness': 0.799,
      'valence': 0.625,
      'tempo': 148.14,
      'type': 'audio_features',
      'id': '6or1bKJiZ06IlK0vFvY75k',
      'uri': 'spotify:track:6or1bKJiZ06IlK0vFvY75k',
      'track_href': 'https://api.spotify.com/v1/tracks/6or1bKJiZ06IlK0vFvY75k',
      'analysis_url': 'https://api.spotify.com/v1/audio-analysis/6or1bKJiZ06IlK0vFvY75k',
      'duration_ms': 363521,
      'time_signature': 4,
      'track_name': 'Rap God',
      'artist': 'Eminem'
    },
    {
      'danceability': 0.39,
      'energy': 0.649,
      'key': 2,
      'loudness': -5.163,
      'mode': 1,
      'speechiness': 0.0345,
      'acousticness': 0.172,
      'instrumentalness': 0,
      'liveness': 0.216,
      'valence': 0.144,
      'tempo': 121.16,
      'type': 'audio_features',
      'id': '6lEuFGrUqR9Yc6hSsHPnYP',
      'uri': 'spotify:track:6lEuFGrUqR9Yc6hSsHPnYP',
      'track_href': 'https://api.spotify.com/v1/tracks/6lEuFGrUqR9Yc6hSsHPnYP',
      'analysis_url': 'https://api.spotify.com/v1/audio-analysis/6lEuFGrUqR9Yc6hSsHPnYP',
      'duration_ms': 299760,
      'time_signature': 4,
      'track_name': `I Don't Want to Miss a Thing`,
      'artist': 'Aerosmith'
    },
    {
      'danceability': 0.367,
      'energy': 0.452,
      'key': 10,
      'loudness': -10.422,
      'mode': 1,
      'speechiness': 0.0307,
      'acousticness': 0.0353,
      'instrumentalness': 0.00228,
      'liveness': 0.689,
      'valence': 0.189,
      'tempo': 113.066,
      'type': 'audio_features',
      'id': '54X78diSLoUDI3joC2bjMz',
      'uri': 'spotify:track:54X78diSLoUDI3joC2bjMz',
      'track_href': 'https://api.spotify.com/v1/tracks/54X78diSLoUDI3joC2bjMz',
      'analysis_url': 'https://api.spotify.com/v1/audio-analysis/54X78diSLoUDI3joC2bjMz',
      'duration_ms': 520787,
      'time_signature': 4,
      'track_name': `Purple Rain`,
      'artist': 'Prince'
    },
    {
      'danceability': 0.62,
      'energy': 0.93,
      'key': 1,
      'loudness': -3.685,
      'mode': 1,
      'speechiness': 0.0374,
      'acousticness': 0.00043,
      'instrumentalness': 0,
      'liveness': 0.0686,
      'valence': 0.609,
      'tempo': 106.22,
      'type': 'audio_features',
      'id': '2g2a5kDeZexbUTD8abcvm6',
      'uri': 'spotify:track:2g2a5kDeZexbUTD8abcvm6',
      'track_href': 'https://api.spotify.com/v1/tracks/2g2a5kDeZexbUTD8abcvm6',
      'analysis_url': 'https://api.spotify.com/v1/audio-analysis/2g2a5kDeZexbUTD8abcvm6',
      'duration_ms': 190173,
      'time_signature': 4,
      'track_name': `Lifestyles of the Rich & Famous`,
      'artist': 'Good Charlotte'
    },
    {
      'danceability': 0.618,
      'energy': 0.938,
      'key': 9,
      'loudness': -3.442,
      'mode': 1,
      'speechiness': 0.0456,
      'acousticness': 0.0179,
      'instrumentalness': 0,
      'liveness': 0.167,
      'valence': 0.875,
      'tempo': 91.455,
      'type': 'audio_features',
      'id': '3ZOEytgrvLwQaqXreDs2Jx',
      'uri': 'spotify:track:3ZOEytgrvLwQaqXreDs2Jx',
      'track_href': 'https://api.spotify.com/v1/tracks/3ZOEytgrvLwQaqXreDs2Jx',
      'analysis_url': 'https://api.spotify.com/v1/audio-analysis/3ZOEytgrvLwQaqXreDs2Jx',
      'duration_ms': 269000,
      'time_signature': 4,
      'track_name': `Can't stop`,
      'artist': 'Red Hot Chilli Peppers'
    },
    {
      'danceability': 0.768,
      'energy': 0.864,
      'key': 11,
      'loudness': -6.145,
      'mode': 1,
      'speechiness': 0.0324,
      'acousticness': 0.101,
      'instrumentalness': 0,
      'liveness': 0.162,
      'valence': 0.891,
      'tempo': 110.008,
      'type': 'audio_features',
      'id': '1Je1IMUlBXcx1Fz0WE7oPT',
      'uri': 'spotify:track:1Je1IMUlBXcx1Fz0WE7oPT',
      'track_href': 'https://api.spotify.com/v1/tracks/1Je1IMUlBXcx1Fz0WE7oPT',
      'analysis_url': 'https://api.spotify.com/v1/audio-analysis/1Je1IMUlBXcx1Fz0WE7oPT',
      'duration_ms': 173027,
      'time_signature': 4,
      'track_name': `Wannabe`,
      'artist': 'Spice Girls'
    },
    {
      'danceability': 0.432,
      'energy': 0.781,
      'key': 4,
      'loudness': -4.038,
      'mode': 0,
      'speechiness': 0.0567,
      'acousticness': 0.041,
      'instrumentalness': 0.00000421,
      'liveness': 0.0789,
      'valence': 0.197,
      'tempo': 139.432,
      'type': 'audio_features',
      'id': '66hayvUbTotekKU3H4ta1f',
      'uri': 'spotify:track:66hayvUbTotekKU3H4ta1f',
      'track_href': 'https://api.spotify.com/v1/tracks/66hayvUbTotekKU3H4ta1f',
      'analysis_url': 'https://api.spotify.com/v1/audio-analysis/66hayvUbTotekKU3H4ta1f',
      'duration_ms': 250286,
      'time_signature': 4,
      'track_name': `Where Are U Now (with Justin Bieber)`,
      'artist': 'Skrillex'
    }
  ]
}
